### ISSUE TITLE
ev_reader.cpp is a binary file

### ISSUE THREAD

**Issue by austonst** [ztzhang/SoundSynth#1]
The file file_generator/ev_reader.cpp appears to be a compiled binary file instead of a C++ source file. This breaks the compile_cpps.sh script as well as all of the auto_install.sh scripts that depend on it.

Should be resolvable by uploading the original C++ source file in its place.

**Comment by ztzhang** [comment]
Thanks!
It seems this function is deprecated. Removing it from repo.
